class InternalError(Exception):
    pass

class SemanticError(Exception):
    pass